# Generated by Django 2.1.15 on 2020-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candi_cnt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='crim_cnt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tax_5y',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tax_defalt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tax_total',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='wealth',
            field=models.CharField(max_length=50),
        ),
    ]
