# Generated by Django 2.1.15 on 2020-04-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0002_auto_20200402_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='adress',
            new_name='address',
        ),
    ]
