# Generated by Django 2.2 on 2020-04-03 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0003_auto_20200402_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precinct',
            old_name='lawlocation',
            new_name='admin_location',
        ),
        migrations.AddField(
            model_name='precinct',
            name='sigun',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
