# Generated by Django 2.1.15 on 2020-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0004_auto_20200403_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_location', models.CharField(max_length=20)),
                ('precint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl_elect.Precinct')),
            ],
        ),
    ]
