# Generated by Django 2.2 on 2020-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0004_auto_20200403_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precinct',
        ),
    ]
