# Generated by Django 2.1.15 on 2020-04-04 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0006_auto_20200404_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gusigun',
            name='precint',
        ),
        migrations.RenameField(
            model_name='precinct',
            old_name='admin_location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='precinct',
            old_name='election',
            new_name='dong',
        ),
        migrations.AddField(
            model_name='precinct',
            name='sgg',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gusigun',
        ),
    ]
