# Generated by Django 2.1.15 on 2020-04-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0007_auto_20200404_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precinct',
        ),
    ]
