# Generated by Django 2.2 on 2020-04-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0009_precinct'),
        ('crawl_elect', '0005_delete_precinct'),
    ]

    operations = [
    ]
