# Generated by Django 2.2 on 2020-04-05 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0010_merge_20200405_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('sigun', models.CharField(max_length=20)),
                ('dong', models.CharField(max_length=20)),
                ('sgg', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='detail_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
