# Generated by Django 2.2 on 2020-04-05 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0011_auto_20200405_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gong_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
