# Generated by Django 2.2 on 2020-04-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0012_candidate_gong_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep', models.CharField(max_length=20)),
                ('pic', models.CharField(max_length=200)),
                ('belong', models.CharField(max_length=30)),
                ('suggest_num', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=50)),
                ('career', models.CharField(max_length=100)),
                ('wealth', models.CharField(max_length=50)),
                ('military', models.CharField(max_length=50)),
                ('tax_total', models.CharField(max_length=50)),
                ('tax_5y', models.CharField(max_length=50)),
                ('tax_defalt', models.CharField(max_length=50)),
                ('crim_cnt', models.CharField(max_length=50)),
                ('candi_cnt', models.CharField(max_length=50)),
                ('detail_url', models.CharField(max_length=250)),
                ('gong_url', models.CharField(max_length=250)),
            ],
        ),
    ]
