# Generated by Django 2.2 on 2020-04-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0013_brae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg_date', models.CharField(max_length=15)),
                ('boss', models.CharField(max_length=15)),
                ('locate', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=20)),
            ],
        ),
    ]
