# Generated by Django 2.2 on 2020-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_elect', '0014_jd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jd',
            name='boss',
            field=models.CharField(max_length=50),
        ),
    ]
